In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from fbprophet import Prophet
df=pd.read_csv("https://github.com/HamoyeHQ/HDSC-Time-series-analysis-and-forecast/files/7768846/Time_series_analysis_and_forecast_DATASET.csv")
df.describe()
# df[ "Month" ] = pd.to_datetime(df[ "Month" ]) #convert column to datetime
# df.set_index( "Month" , inplace= True )
# plt.figure(figsize=( 10 , 6 ))
# plt.plot(df.index, df.Passengers, '--' , marker= '*' , )
# plt.grid()
# plt.xlabel( 'Year' )
# plt.ylabel( 'Passengers' )

               Tmax       SysLoad      GasPrice     ElecPrice
count  92016.000000  92016.000000  92016.000000  92016.000000
mean     231.696688    797.623357      6.016163     65.798356
std     4562.128748    613.520156      2.608116    213.144084
min        9.900000  -1596.810100      0.000000   -924.820000
25%       17.300000    417.119800      3.936900     31.543750
50%       21.900000    856.467925      5.165600     48.715000
75%       27.600000   1221.293675      8.023300     76.495000
max    99999.900000   3264.166300     29.990000  14700.000000

In [23]:
df.isnull().values.any()

False